### ISSUE TITLE
Meeseeks is using the HTML parser, not the XML parser

### ISSUE THREAD

**Issue by mischov** [qcam/saxy-bench#2]
Just noticed this, and I don’t expect that it’d make too much of a difference to saxy being faster, but `Meeseeks.parse(xml)` will use the HTML5 compliant parser not the XML parser.

To use the XML parser you want to call `Meeseeks.parse(xml, :xml)`.

**Comment by qcam** [comment]
👍 Thanks for pointing that out.

The benchmark suite has been moved to the Saxy repo for a while, and I've decided to take Meeseeks off the benchmarking. It was very unfair to compare SAX parsers only accumulating events to a parser building DOM trees. Even though I have tried to emphasize that users should always benchmark against their own XML documents, having Meeseeks is still more misleading than helpful to users.

Just in case you are interested, I've made some (very unfair) benchmark against Meeseeks

```
Operating System: macOS
CPU Information: Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
Number of Available Cores: 4
Available memory: 16 GB
Elixir 1.10.2
Erlang 23.0.3

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 10 s
memory time: 2 s
parallel: 1
inputs: samples/30mb.xml, samples/hackernoon.xml, samples/reddit.xml, samples/soccer.xml
Estimated total run time: 1.87 min

Benchmarking Meeseeks (orange) with input samples/30mb.xml...
Benchmarking Meeseeks (orange) with input samples/hackernoon.xml...
Benchmarking Meeseeks (orange) with input samples/reddit.xml...
Benchmarking Meeseeks (orange) with input samples/soccer.xml...
Benchmarking Saxy (apple) with input samples/30mb.xml...
Benchmarking Saxy (apple) with input samples/hackernoon.xml...
Benchmarking Saxy (apple) with input samples/reddit.xml...
Benchmarking Saxy (apple) with input samples/soccer.xml...

##### With input samples/30mb.xml #####
Name                        ips        average  deviation         median         99th %
Saxy (apple)               0.40         2.49 s    ±36.20%         2.07 s         3.83 s
Meeseeks (orange)          0.20         4.91 s    ±20.22%         4.91 s         5.61 s

Comparison:
Saxy (apple)               0.40
Meeseeks (orange)          0.20 - 1.97x slower +2.42 s

Memory usage statistics:

Name                 Memory usage
Saxy (apple)            219.03 MB
Meeseeks (orange)       150.76 MB - 0.69x memory usage -68.26667 MB

**All measurements for memory usage were the same**

##### With input samples/hackernoon.xml #####
Name                        ips        average  deviation         median         99th %
Saxy (apple)             232.17        4.31 ms    ±13.35%        4.17 ms        6.79 ms
Meeseeks (orange)         46.30       21.60 ms    ±50.45%       20.41 ms       44.02 ms

Comparison:
Saxy (apple)             232.17
Meeseeks (orange)         46.30 - 5.01x slower +17.29 ms

Memory usage statistics:

Name                 Memory usage
Saxy (apple)             62.70 KB
Meeseeks (orange)        39.99 KB - 0.64x memory usage -22.71094 KB

**All measurements for memory usage were the same**

##### With input samples/reddit.xml #####
Name                        ips        average  deviation         median         99th %
Saxy (apple)             375.39        2.66 ms   ±464.98%        1.98 ms        2.96 ms
Meeseeks (orange)        275.18        3.63 ms   ±269.33%        3.31 ms        4.52 ms

Comparison:
Saxy (apple)             375.39
Meeseeks (orange)        275.18 - 1.36x slower +0.97 ms

Memory usage statistics:

Name                 Memory usage
Saxy (apple)            255.26 KB
Meeseeks (orange)       146.88 KB - 0.58x memory usage -108.37500 KB

**All measurements for memory usage were the same**

##### With input samples/soccer.xml #####
Name                        ips        average  deviation         median         99th %
Saxy (apple)              11.53       86.70 ms    ±64.48%       67.14 ms      267.33 ms
Meeseeks (orange)          7.34      136.23 ms    ±85.87%      102.78 ms      735.25 ms

Comparison:
Saxy (apple)              11.53
Meeseeks (orange)          7.34 - 1.57x slower +49.53 ms

Memory usage statistics:

Name                 Memory usage
Saxy (apple)              8.97 MB
Meeseeks (orange)         5.80 MB - 0.65x memory usage -3.16879 MB

**All measurements for memory usage were the same**
```

That's very impressive that Meeseeks is only slightly slower even it has done much more work (with much less memory)!

**Comment by mischov** [comment]
Very cool. Those are better results than I expected.

The other day I saw a video about parsing and selecting XML that benchmarked Saxy, and I cloned [the repo](https://github.com/Plangora/xml_parse/tree/benchmark) and tested Meeseeks out of curiousity to see how it would stack up, and for that benchmark Saxy was about 5x as fast and used half the memory. Admittedly that benchmark probably isn't particularly meaningful because the XML benchmarked is ~200 bytes!

I am still curious how things would compare in a more realworld parse+select example but there's no doubting that Saxy is _very_ good at what it does.

Edit: And I'm excited to see how Saxy improves with the JIT!

**Comment by qcam** [comment]
I totally agree with you, benchmarking XML documents is hard since the result really depends on the documents itself. 

Usually Saxy performs quite well with deeply nested documents and slightly less well on simpler documents such `<?xml version="1.0"?><foo>bar</foo>`. In addition Saxy supports stopping the parser at almost anywhere in the document: in case we are only interested in the first few tags of an extremely long document, I think Saxy or any SAX parsers would likely top a DOM parser in that case.

And yes, I'm also excited to see how Saxy would improve with the JIT! Previously when I was benchmarking Saxy encoder against OTP 22, the result was 7x times faster than Saxy on OTP 20. OTP is amazing!
